#!/bin/bash

body="{\"bri\": $2}"

http="PUT /api/-UaDNHD5j44y07zYdAOEg0JuIakQpu72ivJXXHVS/lights/2/state HTTP/1.1\r\nHost: 192.168.188.26\r\nAccept: */*\r\nContent-Type: application/x-www-form-urlencoded\r\nContent-Length: ${#body}\r\n\r\n${body}\r\n"
echo -e "$http" | telnet $1 80


